export const FETCH_FLICKR_START = 'FETCH_FLICKR_START'
export const FETCH_FLICKR_SUCCESS = 'FETCH_FLICKR_SUCCESS'
export const FETCH_FLICKR_FAILURE = 'FETCH_FLICKR_FAILURE'

export const FETCH_OWNER_INFO_START = 'FETCH_OWNER_INFO_START'
export const FETCH_OWNER_INFO_SUCCESS = 'FETCH_OWNER_INFO_SUCCESS'
export const FETCH_OWNER_INFO_FAILURE = 'FETCH_OWNER_INFO_FAILURE'
